### PR TITLE
Add decisions list UI with filtering, sorting & pagination

### LINKED ISSUE #3707: Decisions: Create Decisions List on Decisions page (UI Only)
### Story
As a user I want to see the list of Decisions, on the Decision page. 

This should be based upon: #3706
### Design
Figma: https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=1018%3A56590

Screenshot 2022-08-02 at 12 16 47

### This issue is complete when
- [ ] Shows list of Decisions
- [ ] Decisions list item with route

### PR DESCRIPTION
**Pull request by chinins**
## Description

This PR adds UI for the decisions list page including filtering, sorting and pagination functionality.

I've added props to the ActionsListItem component as it seems only logical to reuse it. 

I've added `Notice` motions state. It is a state that will be given only for the `Notice` tag. It means that the decision has been staked.

Screenshot 2022-08-09 at 17 04 43
 
resolves #3707

### CODE REVIEW

**Review by ArmandoGraterol — APPROVED** [review]
9c5

**Review by Julianahlk — APPROVED** [review]
LGTM 👍

**Review by danbr — CHANGES_REQUESTED** [review]
Filtering looks good. 
The sorting doesnt change order. Perhaps this is due missing time/date data.

Also the dapp is crashing when loading the page without the governance extension installed.

Screenshot 2022-08-11 at 08 57 02

**Review by danbr — APPROVED** [review]
Looking good.... all working well. Nice work.

**Comment by chinins** [comment]
> Filtering looks good. The sorting doesnt change order. Perhaps this is due missing time/date data.
> 
> Also the dapp is crashing when loading the page without the governance extension installed.
> 
> Screenshot 2022-08-11 at 08 57 02

Good catch - fixed everything. Once I have the final design & copy  from Arren about extension installation, I'll add the final touches. But these will be really minor fixes.

**Pull request merged**
