### PR TITLE
Improve border radius on avatar hover

### LINKED ISSUE #3350: Border issue on Avatar hover
## Steps to reproduce

1. Go to the Actions page of any colony and hover over the avatar.
2. You should see that there is a padding issue around the avatar.

## Expected behaviour

* The border around the avatar should be flush with the avatar

## Actual behaviour

* The border around the avatar is not flush with the avatar

9d1e7d98-a864-47e1-893a-0e00cec543da

### PR DESCRIPTION
**Pull request by arrenv**
## Description

This PR aims to improve the hover of the avatar in the actions items list. There is a background color added to improve the rendering inconsistencies. It is not pretty still, but I feel it looks better. Feel free to provide any other suggestions.

b183135f-ce61-4b78-8963-87a4634aac9f

**Changes** 🏗

* Adjust size of avatar
* Added background color to avatar on hover.

Resolves #3350

### CODE REVIEW

**Review by rdig — APPROVED** [review]
Good to go! :+1

**Review by chinins — APPROVED** [review]
Short and sweet!

**Review by danbr — APPROVED** [review]
Easy-peasie.........LGTM - well done!

**Review by ArmandoGraterol — APPROVED** [review]
I too like to approve short PRs :+1: 

(Tbh I don't see any difference but that's most likely it's just me)

**Pull request merged**
