### PR TITLE
Improve Token Activation popover styles

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
Improved some of the styles of the Token Activation popover

* Aligned token avatar to the center
* Updated padding and margin so that it looks more like the specs
* Updated max button font weight
* Improved alignment of Confirm button and wallet address button

FireShot Capture 305 - Colony - localhost

Resolves DEV-327

### CODE REVIEW

**Review by alicjakujawa — COMMENTED** [review]
What designs you was using for updating styles in here? https://www.figma.com/file/m96yJW1PPXezFl2mkuYha6/Token-Activation?node-id=1275%3A0 i see here, that popover looks a bit different (for example "Staked" aligment) and some other things

**Comment by ArmandoGraterol** [comment]
> What designs you was using for updating styles in here? https://www.figma.com/file/m96yJW1PPXezFl2mkuYha6/Token-Activation?node-id=1275%3A0 i see here, that popover looks a bit different (for example "Staked" aligment) and some other things

I was using this one: https://www.figma.com/file/m96yJW1PPXezFl2mkuYha6/Token-Activation?node-id=1689%3A7694

As that is the one I see marked as a "Reference"

**Review by chinins — COMMENTED** [review]
What about the 2 buttons: activate and deactivate? i think there is the same problem of vertical text align as was with the confirm button

**Comment by ArmandoGraterol** [comment]
> What about the 2 buttons: activate and deactivate? i think there is the same problem of vertical text align as was with the confirm button

Hmmm, that's true. 

They only mentioned the Confirm button so I tunneled down on that. I will adjust the other 2 buttons tomorrow

**Review by rdig — CHANGES_REQUESTED** [review]
I'm mostly good with this, but:

1. Confirm button looks correct:
Screenshot from 2021-05-19 00-14-36

2. However the Activate/Deactivate buttons do not look aligned proper:
Screenshot from 2021-05-19 00-14-39

3. Shouldn't the staked tokens indicator be aligned to the left on the same column as the other two (active / inactive)
Screenshot from 2021-05-19 00-14-46

**Comment by ArmandoGraterol** [comment]
> I'm mostly good with this, but:
> 
> 1. Confirm button looks correct:
>    Screenshot from 2021-05-19 00-14-36
> 2. However the Activate/Deactivate buttons do not look aligned proper:
>    Screenshot from 2021-05-19 00-14-39
> 3. Shouldn't the staked tokens indicator be aligned to the left on the same column as the other two (active / inactive)
>    Screenshot from 2021-05-19 00-14-46

3.Well, in the reference screen the yellow dot is aligned with the "Activate" and "Deactivate" text ... I guess they want to convey that it's a subcategory of active tokens?

**Review by chinins — APPROVED** [review]
Looks good to me! Indeed, the yellow dot was supposed to be moved to the right from the very beginning.

**Review by alicjakujawa — APPROVED** [review]
Screenshot 2021-05-20 at 15 29 05
Small nitpick - just make sure that title is in line with avatar, but apart of this im approving 🔥

**Pull request merged**
