### PR TITLE
Add Unlock Token action to the Actions List

### LINKED ISSUE #2816: Add Unlock Token action to the Actions List
### * SEE BRIEF NEXT COMMENT DOWN

Outline:
- update `subgraph` to fetch the new event _(if we don't fetch it already)_ -- with might not be able to do so, so inquire with Alex
- If new event, add event types
- If new event, add event copy
- Update query _(subescription)_ to display this event as well
- Process required data inside the transformer
- I think that's it ?

Note: it's ok that this will redirect to 404, as the page to handle it has not been built yet

### PR DESCRIPTION
**Pull request by danbr**
## Description

- This PR adds unlock native token action to the Action List page.

**New stuff** ✨

- Update SubgraphEventsThatAreActions subscription

Resolves #2816

Screenshot 2022-01-11 at 21 29 37

### CODE REVIEW

**Comment by dit7ya** [comment]
I cannot reproduce this on my end.

Steps taken:

1. `gh pr checkout 3094`
2. Run heavy dev server
3. Create colony
4. Mint token
5. New Action -> Manage Funds -> Unlock Token

Nothing appears on the All Teams Actions view.

Screenshot 2022-01-12 at 11-17-01 Colony

**Comment by arrenv** [comment]
@dit7ya, @danbr will likely need to follow @chinins comment here https://github.com/JoinColony/colonyDapp/pull/3081 or rebase with the `feature/unlock-token-action` branch.

Then you will need to do `npm run provision` before initiating.

**Review by arrenv — APPROVED** [review]
Working well!

unlock-token-in-actions

**Review by ArmandoGraterol — APPROVED** [review]
Looking good! Nice work

**Pull request merged**
