### PR TITLE
Update step 3 of adding a safe

### LINKED ISSUE #4083: Update Step 3 of the Add a Safe process
**EDIT: SEE COMMENT BELOW**

### Description

To help make it more clear what to do in Step 3 of the process, the title has been updated, a question mark has been added and the link has been fixed. Also a typo has also been fixed in the validation error message

The title text should now be - "Step 3: Provide module address and add Safe"

The "Where to find this?" link should go to this - https://colony.gitbook.io/colony/advanced-features/safe-control-gnosis-safe/adding-a-safe#finding-the-module-contract-address

### Design

- [Figma link - Step 3 Updates](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=8138%3A23729&t=1MytesFhwrIVww6u-1)
- [Figma Link - Add capitalisation to Safe](https://www.figma.com/file/LlVmeMQxHVA04evfrgZyuN/Safe-Control?node-id=8138%3A25191&t=1MytesFhwrIVww6u-1)

step-3-updates

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
**Changes** 🏗

* Updated title and link copy of the 3rd step of adding a safe.
* Updated the link of `Where to find this?`.
* Moved bridge module address input and validation to the 2nd step.
* Added tooltip to safe name input label

Resolves #4083

### CODE REVIEW

**Review by Julianahlk — APPROVED** [review]
Looking good 👍

**Review by chinins — APPROVED** [review]
All good!

**Comment by ArmandoGraterol** [comment]
@Julianahlk @chinins This PR and issue have changed a lot since you guys reviewed it, so I would appreciate it if you can review it once more :)

**Review by chinins — APPROVED** [review]
Looking good!

**Review by arrenv — APPROVED** [review]
Looking good to me, thank you @ArmandoGraterol

**Pull request merged**
