### PR TITLE
Add: Extensions details page mobile

### LINKED ISSUE #3557: Create mobile responsive Extensions details screen
## Specification

Relates to #3481 

### Story

When I click on a specific extension (e.g. governance) from the `extensions` screen on mobile, I want the extensions details page to be responsive. 

### Description 

Following the style of the designs (linked in other issues in this project), this issue tracks the work required to make the extensions details screen mobile responsive. 

### Design 

No design for this specific screen but should follow style of other designs in this project. 

### This issue is complete when...

- [ ] The extensions details screen is mobile responsive (`max-width: 768px`)

### PR DESCRIPTION
**Pull request by willm30**
## Description

Relates to #3549 

This PR is for the `ExtensionDetails` page on mobile. On mobile, when you click on an extension to view its details/install it etc., the details page should adapt to the screen.

**Additions**

* Add utility function that waits for a given selector to become present in the DOM. (This is so when you click the "enable" button there's a smooth transition to the start of that section) 

**Changes** 🏗

* Adapt `ExtensionDetails` for mobile
* Adapt `ExtensionSetup` for mobile

Resolves #3557 

**_Extension details_**
extn

**_Extension setup_**
enable-extn

### CODE REVIEW

**Comment by willm30** [comment]
@Julianahlk I would have said that's expected behaviour, i.e it maintains its position beneath the kebab icon at various screen widths (per GIF): 
colony-popover

**Comment by Julianahlk** [comment]
> 

Cool, sounds good! Just making sure. 😊

**Review by chinins — APPROVED** [review]
All good!

**Review by ArmandoGraterol — APPROVED** [review]
LGTM :ok_hand:

**Pull request merged**
