### PR TITLE
Add title and description of expenditure

### LINKED ISSUE #3411: Expenditures: As a User I can change title and description of expenditure
[Provided by Michał via Contractors project management platform]

### Description
User is able to change the title and description of the expenditure.

### Acceptance Criteria

- an to option to change title
- an option to change description
- an option to display title
- an option to display description

### Design
https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=2420%3A1079876
https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=2420%3A1080905

f89574970fb37c27bc772941c38b6b21

f89a30abb2a08fe8b259fffdfd4e332b

### PR DESCRIPTION
**Pull request by agnieszkajarosikloj**
## Description
This PR adds section with title and description of expenditure. If title and description aren't provided or form is in edit state, there are inputs where these values ​​can be set. If the title and description are set, this section just displays them.

[Figma design - empty form](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures)
[Figma design - set values](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=2420%3A1080905)

**New stuff** ✨

Screenshot 2022-05-30 at 00 08 36

Screenshot 2022-05-30 at 00 09 24

## TODO

- add actual expenditure number

Resolves #3411

### CODE REVIEW

**Review by arrenv — CHANGES_REQUESTED** [review]
@agnieszkajarosikloj Can we please make the description a textarea input.

Can we also move this content down to be in line with the top of the settings content.

36618198-c791-45ac-a80b-1506839bfd45

**Review by arrenv — CHANGES_REQUESTED** [review]
Thank you @agnieszkajarosikloj. Looking at how the description works, it would be good to have the textarea height autogrow.

46f8e655-40d5-4747-8b70-0ac87c8a57f8

**Review by arrenv — APPROVED** [review]
Looks good to me, thanks @agnieszkajarosikloj

**Review by chinins — COMMENTED** [review]
Looks good - nice work!

**Review by chinins — APPROVED** [review]
Wanted to approve with my previous comment. Sorry for confusion.

**Review by rdig — COMMENTED** [review]
At least code wise, this looks good. Nice job!

**Pull request merged**
