### PR TITLE
Change Numbro abbreviations and number formatting

### LINKED ISSUE #3168: Change Numbro abbreviations to use uppercase.
Currently, the abbreviations used within Numbro are based on locale files. For most, if not all locales for English speaking countries use lowercase abbreviations.

https://github.com/BenjaminVanRyseghem/numbro/tree/develop/languages

Confirm with Product that they require English language locales to use uppercase abbreviations. 

For example:

  abbreviations: {
        thousand: "K,
        million: "M,
        billion: "B",
        trillion: "T"
    },

If confirmed, create Colony locale file, and update the code to utilise.

Please branch off refactor/3126-numeral-component

### PR DESCRIPTION
**Pull request by arrenv**
## Description

This PR adds some number formatting changes and a custom language file for Numbro, which is the only way to change the abbreviation, it seems.

I put the language file alongside the `numberFormatter.ts` file for lack of a better location, and I don't see many reasons to have multiple language files for this purpose. I did try to utilise the existing `react-intl`, however, this seems like it will require quite a bit of refactoring (unless someone has an idea here)

number_formatting

**Expected number format**
- Abbreviation starts at 1 million
- All numbers are to have 6 max digits, so, abbreviated numbers will have 5 significant decimal places.
- Abbreviation has a thousand separator
- With a capital letter for abbreviation 
- With no space between the abbreviation and the number

**New stuff** ✨

* Adds language file for Numbro
* Registers the newly added language file

**Changes** 🏗

* Changes number formatting to 5 decimal places
* Adds comma separation on numbers larger then a 1 quadrillion.

Resolves #3168

### CODE REVIEW

**Review by chinins — APPROVED** [review]
Looks good!

**Review by ArmandoGraterol — APPROVED** [review]
I think it's good enough as it is, the implementation is simple and easy to understand. If we use `react-intl` we might need to add another package? I've seen some `react-intl-number-formatter-thingy` floating around before

**Review by danbr — APPROVED** [review]
Well done. Looks good.

One thing that caught my eye was the sizing & spacing of the number abbreviation vs the token abbreviation. Guess this needs some thought.

Screenshot 2022-02-25 at 15 30 09

Screenshot 2022-02-25 at 15 27 45

It works well here, better than the total
Screenshot 2022-02-25 at 15 29 04

And also, the tokensActivationPopover where real estate is limited, can be abbreviated (outside the scope of this PR)
Screenshot 2022-02-25 at 15 30 17

**Comment by arrenv** [comment]
> One thing that caught my eye was the sizing & spacing of the number abbreviation vs the token abbreviation. Guess this needs some thought.

From the product sync, we had the idea to show the main balance as the full number, so, maybe that would solve this visual inconsistency.

**Pull request merged**
