### PR TITLE
Fix: max button overflow

### LINKED ISSUE #3690: Bug: large number overflows "max" label in Input container
## Steps to reproduce

1. Go to smite reputation in the actions menu
2. Enter a very large number such that it overlaps the "max" label

## Expected behaviour

* Number does not overlap the "max" label

## Actual behaviour

* Number overlaps

max-overflow

### PR DESCRIPTION
**Pull request by willm30**
## Description

- This PR prevents very long numbers overlaying the max button when it is present in an input component.

**Changes** 🏗

* Add padding to input when max button is present.

## Screenshots 

max-overflow-fix

Resolves  #3690

### CODE REVIEW

**Review by danbr — APPROVED** [review]
LGTM 👍 

Its outside the scope of this PR, but maybe a standard approach can also be taken with inputs (without Max button). Its very minor....

Screenshot 2022-07-28 at 21 37 51

**Comment by Julianahlk** [comment]
Looks good 👍
Screen Shot 2022-07-29 at 12 39 35 AM

**Review by Julianahlk — APPROVED** [review]

**Review by chinins — APPROVED** [review]
Short & sweet.

**Review by arrenv — CHANGES_REQUESTED** [review]
@willm30 I don't think this is the best way to fix this, this impacts all inputs.

For example:

ffb9e52e-6148-4018-8f24-0e44ac9c6aa3

**Comment by chinins** [comment]
> @willm30 I don't think this is the best way to fix this, this impacts all inputs.
> 
> For example:
> 
Great catch arren.

**Comment by willm30** [comment]
@arrenv I've updated to use the `.maxButton` class so should now be working as intended.

**Review by ArmandoGraterol — APPROVED** [review]
Looks good! All the other inputs are looking as expected :+1:

**Comment by willm30** [comment]
@arrenv Is this looking good for you now?

**Review by arrenv — APPROVED** [review]
Looks good, thanks for your patience Will, I seemed to have missed the update.

**Pull request merged**
