### PR TITLE
Coin Machine Buy Tokens Widget

### PR DESCRIPTION
**Pull request by rdig**
## Description

This PR implements the "Buy Tokens" widget to the Coin Machine page, that allows the user the ability to purchase a certain amount of tokens in the current sale interval.

**Note** that this escalated is scope from when it was initially spec'd out, due to the previous team's failure to implement it's UI originally. See #2206 if you think you can find it.

**Testing**
- Create a colony
- Mint tokens _(1000+)_
- Unlock the token
- Install Coin Machine 
- Enable with _Default Values_
- Send 100+ tokens to the Coin Machine contract _(copy the contract address and create a payment action, with the address as a recipient)_
- Go buy some tokens on the Coin Machine page
- **Note that you can only buy a max of 100 tokens per period, so if you reach that limit, the buy widget will not allow you to buy more, until the next period starts _(and since we don't have UI for that yet, you won't be able to tell)_**

**Changes**
- [x] Cherry picked `QuestionMarkTooltip` from the #2413 branch
- [x] Added global `learnMore` message descriptor _(and replaced it where it was being used)_
- [x] Fixed `Chat` component shadow
- [x] Fixed core `Heading` `medium` appearance size letter spacing _(to be in line with the spec)_
- [x] Added `BuyTokens` component
- [x] Added Coin Machine sagas layout
- [x] Added Coin Machine `buyTokens` saga
- [x] Added Coin Machine redux actions and types
- [x] Added Coin Machine resolvers
- [x] Added Coin Machine GraphQL queries and typedefs

**Demo**
demo-cm-buy-tokens

Resolves DEV-245

### CODE REVIEW

**Review by alicjakujawa — CHANGES_REQUESTED** [review]
Looks good! only spotted one bug when was testing with other colony token as a purchase token, see:
Screenshot 2021-07-28 at 16 23 00

**Comment by rdig** [comment]
@alicjakujawa Fixed. 

Please pull the latest changes and test again, as now the buy of native tokens _(with other native tokens)_ should work as expected.

Here's a demo:

demo-cm-buy-native-tokens

**Review by alicjakujawa — APPROVED** [review]

**Review by chinins — APPROVED** [review]
Great job! 🔥

**Review by ArmandoGraterol — APPROVED** [review]
A lot of hard work here! Looks good to me :100:

**Pull request merged**
