### PR TITLE
White in get whitelisted logic

### PR DESCRIPTION
**Pull request by alicjakujawa**
## Description

This PR wire in get whitelisted logic

**New stuff** ✨

* userStatus query
* GetWhitelisted component
* sign agreement action types and saga
* Added SynapsKYCDialog placeholder

**Changes** 🏗

* Updated whitelistPolicy query
* Updated CompleteKYCDialog

**Note** ⚰️

*  Synaps integration was supposed to be done in this issue, but we dont have yet answers from product team so it will be handled in separate, leaving placeholder - SynapsKYCDialog
* Flow for dialogs was updated (made more basic). We just display KYC AND/OR Agreement modal when entering buy tokens page (no additional steps/actions)

Resolves DEV-463

### CODE REVIEW

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
With the `KYC and agreement only` policy selected 2 "Complete KYC" dialogs appear on the Buy Tokens page, 1 on top of the other

**Review by chinins — APPROVED** [review]
Looks good to me. And works properly, it seems. I tried to replicate Armando's 2 dialogs problem but I don't see 2 at the same time...

Very nice work!!! 🔥

**Comment by alicjakujawa** [comment]
@ArmandoGraterol should be fixed now :D

**Review by ArmandoGraterol — APPROVED** [review]
Working as expected now :ok_hand: Nice work!

**Pull request merged**
