### PR TITLE
Fix alignment of the wallet text in wizard

### LINKED ISSUE #2836: Fix alignment of the wallet text in wizard
## Steps to reproduce

1. Navigate to /create-colony page

## Expected behaviour

* Should be aligned, or utilise the UserNavigation component

## Actual behaviour

* Misaligned text in wallet text in header of create colony wizard

header-alignment

## Suggestions

* Replace with the UserNavigation component

### PR DESCRIPTION
**Pull request by arrenv**
## Description

Improve the alignment of the text in the wizard.

**Changes** 🏗

* Removed absolute positioning and utilised CSS Flexbox for improved alignment

update-header-text-in-wizard

Resolves #2836

### CODE REVIEW

**Comment by rdig** [comment]
What issue is this fixing ?

**Comment by rdig** [comment]
I'm assuming it's #2836 ?

**Review by rdig — APPROVED** [review]
Very nice first PR! :tada:

Good to go!

Screenshot from 2021-11-08 15-57-50
Screenshot from 2021-11-08 15-57-57
Screenshot from 2021-11-08 15-58-18
Screenshot from 2021-11-08 15-58-24

**Review by chinins — APPROVED** [review]
Nice work! Good to go :)

**Pull request merged**
