### PR TITLE
Rename Motions and Disputes Extension

### LINKED ISSUE #3420: Change name of Motions & Disputes Extension in the UI
### Story

As a user, it is confusing as to the immediate purpose of the Motions and Disputes Extension.

### Description

We would like to improve the immediate understanding of what the Motions and Dispute Extension does by renaming it to something more explicit.

The new name for the extension should be `Governance (Reputation Weighted)`

Please check where it is referenced within the Dapp, you will also need to check where it is referenced elsewhere, including GitBook, other repos, etc. and follow up to ensure that is renamed in those locations also.

### PR DESCRIPTION
**Pull request by willm30**
## Description

This PR is to rename the Motions and Disputes extension and all references to it in the Dapp.

**Changes** 🏗

- [x] Change "Motions & Disputes (Reputation)" to "Governance (Reputation Weighted)".
- [x] Change page title at relevant extension routes

## Screenshot

governance

**_Page title updated as well_**
governance-title

## TODO

- [x] Research other locations in which old title may be
- [x] Inform relevant teams
- [x] Create issue documenting the location of other references (#3468)

Resolves  #3420

### CODE REVIEW

**Comment by willm30** [comment]
@arrenv In the pr body, I have listed the locations I have found references to "Motions and Disputes" outside of the Dapp repo. There are two: Gitbook and the whitepaper. 

1. Who should I speak to about getting it chaged in gitbook?
2. I'm not sure if it needs changing in the whitepaper, because the whitepaper is referring to the system at a conceptual level not the specific extension. Thoughts?

**Comment by arrenv** [comment]
Thanks @willm30.

1. I can update changes in GitBook. I will time it with when we get close to the release that includes this change.
2. Yeah, we should be fine. We don't need to make changes in the Whitepaper.

**Comment by willm30** [comment]
@arrenv Would you like me to make a separate issue for updating it in Gitbook? And then I can submit this PR for review?

**Comment by arrenv** [comment]
> @arrenv Would you like me to make a separate issue for updating it in Gitbook? And then I can submit this PR for review?

Sounds good to me!

**Comment by dit7ya** [comment]
Also in the Dapp - 

https://github.com/joincolony/colonyDapp/blob/83e2ad78654b92b8ee777bb2fd5dba4b1291fbff/src/utils/hooks/useTitle.ts#L98
https://github.com/joincolony/colonyDapp/blob/83e2ad78654b92b8ee777bb2fd5dba4b1291fbff/src/utils/hooks/useTitle.ts#L108

**Review by rdig — APPROVED** [review]
Couldn't find any other instances of this, so I guess it's all good.

However, I _think_ that if the extension itself requires and upgrade, it will still show up as _Voting Reputation_ since that is the name that's coming from `colonyJS`

**Review by chinins — APPROVED** [review]
Good to go!

**Pull request merged**
