### PR TITLE
Staged payment

### LINKED ISSUE #3672: Expenditures: As a user I can edit fund in staged payment
[Provided by Adrian via Contractors project management platform]

## Description
User has to be able to edit staged payment.

## Acceptance Criteria

- an option to display to whom payment is staged
- an option to add max amount of funds
- an option to change currency
- an option to add/delete milestone
- an option to change milestone name
- at least one milestone should always be visible
- an option to display reserve bar that changes when funds are distributed
- an option to display slider below every milestone
- an option to use sliders to adjust funds for milestone
- an option to display milestone funds below slider

## Design

- [Figma Link - Staged payments edit state](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3746%3A314180)

45fc5bdb05e3b2a0e1a4c5e842055dda

### PR DESCRIPTION
**Pull request by agnieszkajarosikloj**
## Description

This PR adds staged payment. New form section has been added with the following fields: 
- UserPickerWithSearch - to choose to whom payment is staged
- Input and TokenSymbolSelector to set max amount of funds and currency
- multiple Milestones section:
   - buttons to add/delete milestone
   - Input to set milestone name
   - reserve bar that changes when funds are distributed
   - slider below every milestone to set funds for milestone
   - amount milestone funds below slider

Screenshot 2022-08-02 at 10 00 58

[Figma Link - Staged payments edit state](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3746%3A314180)

**New stuff** ✨

* New form section, visible after selecting Expenditure type - "Staged",
* Added form validation in Yup for new form section

**Changes** 🏗

* Changed Slider component (like in this [PR](https://github.com/JoinColony/colonyDapp/pull/3676)) by adding possibility to override styling. It has been done by adding four optional props in Slider component:  
```
  handleStyle?: React.CSSProperties;
  dotStyle?: React.CSSProperties;
  railStyle?: React.CSSProperties;
  trackStyle?: React.CSSProperties;
```
These objects override the default styles:
```
 trackStyle={{
          backgroundColor: colors.backgroundColor,
          height: sizes.height,
          ...trackStyle,
        }}
```

Resolves  #3672

### CODE REVIEW

**Review by Julianahlk — CHANGES_REQUESTED** [review]
So far things are looking pretty good! Just noticed the error message in the Max input field is making the token selector go a bit off the container and the error message text is off as well. This error happened when I typed a period (.)

Screen Shot 2022-08-09 at 12 07 47 AM

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
Looking great from my side! Aside from what Juliana already pointed out, I noticed these:
FireShot Capture 692 - Create Expenditure - Colony - wonker - localhost

1. How come whenever I choose `Staged` the amount inputs already have error messages even though I haven't interacted with them? Is that intentional?

2. I believe the trash can icon of the delete button should show the cursor as a `pointer`, otherwise it just gives off the impression that is not clickable.

**Review by ArmandoGraterol — APPROVED** [review]
Looks great! Just take into consideration the small comment I left :)

**Comment by Julianahlk** [comment]
The very first time I go to Staged, I am getting a warning for the unique key:
staged

**Review by willm30 — APPROVED** [review]
LGTM 🙂

**Comment by Julianahlk** [comment]
Working and looking great! Thank you @agnieszkajarosikloj 👍

**Review by Julianahlk — APPROVED** [review]

**Pull request merged**
