### PR TITLE
Add TokenSalesTable component

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
Added TokenSalesTable component to CoinMachine page

**New stuff** ✨

* Expanded props of TableHeader in order to assign custom classes to it without TS yelling at us.
* Added UI for TokenSalesTable component used on CoinMachine

## How to test
1. Just enter the CoinMachine page to see the empty state of the table
2. To check how the table looks with data you could copy-paste this on the table component:

```
const placeholderData = [
    {
      saleEnd: '21/05 18:00',
      amount: 'SOLD OUT',
      price: 0.0009,
      priceStatus: TokenPriceStatuses.PRICE_SOLD_OUT,
    },
    {
      saleEnd: '21/05 17:00',
      amount: 'SOLD OUT',
      price: 0.0008,
      priceStatus: TokenPriceStatuses.PRICE_SOLD_OUT,
    },
    {
      saleEnd: '21/05 16:00',
      amount: '2500/4500',
      price: 0.0007,
      priceStatus: TokenPriceStatuses.PRICE_UP,
    },
  ];
```
And replace where `tableData` is used with `placeholderData`

FireShot Capture 398 - Colony - localhost

FireShot Capture 399 - Colony - localhost

Resolves DEV-455

### CODE REVIEW

**Review by chinins — APPROVED** [review]
Looks good!

**Review by alicjakujawa — CHANGES_REQUESTED** [review]
Screenshot 2021-07-26 at 11 26 04
1.This space is too huge
2. Table itself should have min height, like in designs 
Apart of those 2, looks good!

**Comment by ArmandoGraterol** [comment]
@alicjakujawa I can't replicate that big space between the border and the table headers, for me they are shown with a padding of 6px between the border and the headers. Is your local branch up-to-date? Can you inspect the element and check what's the padding?

**Comment by alicjakujawa** [comment]
> @alicjakujawa I can't replicate that big space between the border and the table headers, for me they are shown with a padding of 6px between the border and the headers. Is your local branch up-to-date? Can you inspect the element and check what's the padding?

Screenshot 2021-07-27 at 16 21 20

Looks fine when i removed height: 100%

**Review by alicjakujawa — CHANGES_REQUESTED** [review]
Screenshot 2021-07-28 at 08 25 39
Something went wrong with last updates, see grey background and error in the console

**Review by alicjakujawa — APPROVED** [review]
Good to merge!

**Comment by alicjakujawa** [comment]
> Good to merge!

Just dont forget, rebase and test it after rebase

**Pull request merged**
