### PR TITLE
Token activation button UI updates

### PR DESCRIPTION
**Pull request by alicjakujawa**
## Description

This PR updates token activation button styles and adds in tooltips with messages

**New stuff** ✨

* Tooltips on hover with description of current state of tokens

**Changes** 🏗

* Updated token activation button and wallet button styles

Screenshot 2021-02-25 at 14 26 06
Screenshot 2021-02-25 at 14 08 01
Screenshot 2021-02-25 at 14 07 31

Resolves DEV-224

### CODE REVIEW

**Review by ArmandoGraterol — APPROVED** [review]
c144eae92d3f92b608bf157d715d645fdfe531bdr1-300-300v2_uhq

**Review by chinins — CHANGES_REQUESTED** [review]
Everything is great except the border (outline css selector) when the button is focused is a different color than the specs.

**Comment by alicjakujawa** [comment]
> Everything is great except the border (outline css selector) when the button is focused is a different color than the specs.

What you mean is different than in specs? im using colony

**Review by chinins — APPROVED** [review]
All good now!

**Pull request merged**
