### PR TITLE
Fix slider limit

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
Fixed slider limit, should now actually stop at the limit of staking

Resolves DEV-339

### CODE REVIEW

**Review by alicjakujawa — CHANGES_REQUESTED** [review]
I think something is still wrong, see screen:
Screenshot 2021-05-14 at 12 51 22
I didint stake, but from what i see, i cannot stake, but limit is showing that max stake for me is "something"

But actually i cannot stake, so the limit should be 0

**Comment by alicjakujawa** [comment]
And addiitonal screen, it can be of course some issues with slider disabled logic

**Review by alicjakujawa — APPROVED** [review]

**Comment by alicjakujawa** [comment]
Approving, because bugs i mentioned wasn't introduce here

**Review by chinins — APPROVED** [review]
I have the same problem as Alicja but if that should be dealt with in a separate PR I am approving

**Pull request merged**
