### PR TITLE
Add validation messages to StakingWidget

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
- Added more validation to StakingWidget according to user's tokens

**New stuff** ✨

* Added `StakingValidationError` component for reusability purposes
* Added validation to staking widget for 2 more cases

**What to test**

First case: If the users have tokens that are inactive, and they don't have enough active tokens to stake, then they shouldn't be able to stake and should see a message telling them that they should activate all their tokens.

Second case: If the users have fewer tokens than what's they are trying to stake, then they shouldn't be able to stake and they should see a message telling them that they don't have enough tokens.

FireShot Capture 302 - Colony - localhost
FireShot Capture 299 - Colony - localhost

Resolves DEV-344

### CODE REVIEW

**Review by alicjakujawa — CHANGES_REQUESTED** [review]
Screenshot 2021-05-17 at 13 59 30
Its not right, i have almost ALL tokens active and i cant either stake or object.

**Comment by ArmandoGraterol** [comment]
> Screenshot 2021-05-17 at 13 59 30
> 
> Its not right, i have almost ALL tokens active and i cant either stake or object.

Hmmm, isn't that the expected behavior? You shouldn't be able to stake if you have ANY inactive token, at least that's what I understood from what Jack said: "if they have some portion of their token balance which is inactive."

**Comment by alicjakujawa** [comment]
> > Screenshot 2021-05-17 at 13 59 30
> > Its not right, i have almost ALL tokens active and i cant either stake or object.
> 
> Hmmm, isn't that the expected behavior? You shouldn't be able to stake if you have ANY inactive token, at least that's what I understood from what Jack said: "if they have some portion of their token balance which is inactive."

It would be super weird, if i have enough active tokens to stake i should be able to stake amount i have (no more, so validation should check this) Please double check with product

**Comment by alicjakujawa** [comment]
I dont think its ready for retesting, still see the issue

**Comment by ArmandoGraterol** [comment]
> I dont think its ready for retesting, still see the issue

Hmmm I just tested it again and it's working as I expected. Did nothing change for you at all?

**Review by alicjakujawa — APPROVED** [review]
Tested again and this time it was working 🚀 No idea why it wasnt before, im sure i pull changes XD  Please dont forget to rebase this branch

**Review by chinins — APPROVED** [review]
Working for me!

**Pull request merged**
