### PR TITLE
Add decision draft list item and dialog to confirm decision deletion

### LINKED ISSUE #3817: Add draft item view to Decisions page
### Story

As a User creating a decision, if they navigate away accidentally while still in draft they may think they have lost their draft decision.

### Description

We are adding an item on the Decision page to show the single draft decision that is sitting in the users local storage. This will only be visible to the user who created it, as it will only be in their local storage. It will always be the first item in the decisions list. It should have the Draft tag as shown in the design.

They will have the option to navigate to and edit the draft decision or delete it.

This will require checking the users local storage every time loading the page. If there is nothing in the local storage for decision then nothing will show.

Clicking on `Delete` will give a confirmation modal, confirming they would like to delete it. Confirming will clear the local storage for the user, removing the draft item from the list of Decisions.

NOTE: This issue https://github.com/JoinColony/colonyDapp/issues/3818 also requires the delete confirmation modal, so, whoever starts this task will need to develop it and the other person may be able to leverage off of it. This modal has also been created in the Expenditures project here - https://github.com/JoinColony/colonyDapp/pull/3561

### Design

- [Figma link - Draft Item](https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=7794%3A57032)
- [Figma Link - Delete Confirmation Modal](https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=8172%3A58073)

Screenshot 2022-09-06 102348

Screenshot 2022-09-06 103644

### LINKED ISSUE #3818: Add delete option to draft Decision
### Story

As a User creating a draft decision, I may no longer want to create a draft decision and may just want to delete it.

### Description

Adding in a `Delete` option to the draft screen for a Decision will allow a user to delete a draft Decision. Allowing them to start over again, or simply stop the process of creating a Decision.

When the user clicks `Delete` it should give a confirmation modal, where they will need to confirm deletion. On confirmation it with clear their local cache and they will be directed back to the main Decisions list page.

NOTE: This issue https://github.com/JoinColony/colonyDapp/issues/3817 also requires the delete confirmation modal, so, whoever starts this task will need to develop it and the other person may be able to leverage off of it. This modal has also been created in the Expenditures project here - https://github.com/JoinColony/colonyDapp/pull/3561

### Design

- [Figma Link - Delete Button](https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=1018%3A55813)
- [Figma Link - Delete Confirmation Modal](https://www.figma.com/file/oRaTwsD5BUH3FJNzoZdSCv/Discussions?node-id=8172%3A58073)

Screenshot 2022-09-06 104028

Screenshot 2022-09-06 103644

### PR DESCRIPTION
**Pull request by chinins**
## Description

This PR adds several things for draft decision management:

- confirm delete dialog 
- new delete button on the preview page
- draft decision item int he decisions list
- confirm delete draft & create a new decision dialog

resolves #3817 
resolves #3818

### CODE REVIEW

**Review by arrenv — APPROVED** [review]
Looking good @chinins. Just one small request.

Can we change these to blue and have the same hover state:

32483240-f9fa52f5f057b3d55fa1f67a5335f618


Like these button:

32483341-bac0f8804c33bb19cbfca75d73d58dee

**Comment by chinins** [comment]
> Looking good @chinins. Just one small request.
> 
> Can we change these to blue and have the same hover state:
> 
> 32483240-f9fa52f5f057b3d55fa1f67a5335f618
> 
> Like these button:
> 
> 32483341-bac0f8804c33bb19cbfca75d73d58dee

Done - your wish is my command :)

**Comment by danbr** [comment]
@chinins Could you possibly rebase? It'll be easier to review, i'm sure you didnt update 38 files.

**Review by danbr — COMMENTED** [review]
Looking good. Functioning well.

@arrenv @chinins But should'nt the buttons be consistant? Their order is swapped on the 2 screens. Or not.........

Screenshot 2022-09-18 at 19 30 58
Screenshot 2022-09-18 at 19 31 12

**Comment by arrenv** [comment]
> @arrenv @chinins But should'nt the buttons be consistant? Their order is swapped on the 2 screens. Or not.........

I agree the order would be better to be consistent, I vote 'Delete', 'Edit' as the order. For the very minor benefit of reducing risk of mis-clicking delete when trying to go publish.

**Comment by danbr** [comment]
> > @arrenv @chinins But should'nt the buttons be consistant? Their order is swapped on the 2 screens. Or not.........
> 
> I agree the order would be better to be consistent, I vote 'Delete', 'Edit' as the order. For the very minor benefit of reducing risk of mis-clicking delete when trying to go publish.

Works for me.......

**Comment by chinins** [comment]
@danbr, rebased and changed the button positioning as you agreed with Arren. You are welcome to review again.

**Review by danbr — APPROVED** [review]
Looks good & working well. Good job.....

**Pull request merged**
