### PR TITLE
Fixes funding link alignment

### LINKED ISSUE #2814: Fix 'Manage Funds' link alignment
The arrow symbol to the left of the the _Manage Funds_ link on the Colony Home is misaligned for some _(all?)_ machines.

This is a cross OS, cross Machine or cross Resolution issue, so please ensure this will render properly no matter on which machine we try to render.

Note that we only support Chorme officially _(and Chrome based browsers unofficially)_ so you don't really have to bother with how it renders on anything else other than Chrome.

The component you need to be targeting is `ColonyTotalFunds`

Here's some examples of the problem:

I'd say this one is "ok-ish" in terms of alignment _(Linux, 1x Pixel Density, 100% Zoom)_
Screenshot from 2021-10-24 22-58-35

But when you zoom in, it starts to break down _(Linux, 1x Pixel Density, 250% Zoom)_
Screenshot from 2021-10-24 23-10-40

However, this one is clearly misaligned _(Linux, 2x Pixel Density, 100% Zoom)_
Screenshot from 2021-10-24 22-58-24

### PR DESCRIPTION
**Pull request by agustif**
## Description
- [x] Fix the alignment of the funding link

**New stuff** ✨
Added a gap: 15px to separate each button on itself Colony total balance / Manage funds

**Changes** 🏗
Moved from margin to flex based align-items: center; for alignment of items.
**Removed** 
Margin for the rightarrowicon

## TODO

- [ x]  Fixes the alignment of the funding link

## Screenshots **Updated**
image
image
image

Resolves #2814

### CODE REVIEW

**Review by alicjakujawa — COMMENTED** [review]
https://www.figma.com/file/qQoBbyyDXkuHwoqHIOGjEu/Colony-Simplified?node-id=825%3A10764

Im not sure, was it a real bug? I see in designs that arrow should be more on top of text

**Review by chinins — CHANGES_REQUESTED** [review]
It's looking fine on my machine with 100% or higher zoom. But it's not looking ok when I zoom out (as per the screens shot). On your screen shots it doesn't look ok on #2 & #3 (the arrow is too high in both). Please, fix this as well.
Screenshot 2021-11-05 at 16 17 27

**Comment by chinins** [comment]
> https://www.figma.com/file/qQoBbyyDXkuHwoqHIOGjEu/Colony-Simplified?node-id=825%3A10764
> 
> Im not sure, was it a real bug? I see in designs that arrow should be more on top of text

It's good point to clarify with Karol. But what Alicja shared looks a bit strange to me - the text is not aligned either, so I'd just confirm with Karol.
Screenshot 2021-11-05 at 16 20 09

**Comment by agustif** [comment]
> > https://www.figma.com/file/qQoBbyyDXkuHwoqHIOGjEu/Colony-Simplified?node-id=825%3A10764
> > Im not sure, was it a real bug? I see in designs that arrow should be more on top of text
> 
> It's good point to clarify with Karol. But what Alicja shared looks a bit strange to me - the text is not aligned either, so I'd just confirm with Karol. Screenshot 2021-11-05 at 16 20 09

Yeah I agree, I will look into using something else instead of margins, like flex or vertical-align or whatever to try to not have to put actual pixels so it works well in *all cases*

**Comment by agustif** [comment]
I added some changes and updated the screenshots, could you re-review? Thanks

New approach should work better on any os/browser/resolutions/dpi whatever I think, no longer using margin moved to flex.

**Comment by agustif** [comment]
> > https://www.figma.com/file/qQoBbyyDXkuHwoqHIOGjEu/Colony-Simplified?node-id=825%3A10764
> > Im not sure, was it a real bug? I see in designs that arrow should be more on top of text
> 
> It's good point to clarify with Karol. But what Alicja shared looks a bit strange to me - the text is not aligned either, so I'd just confirm with Karol. Screenshot 2021-11-05 at 16 20 09

Can you guys re-review, I took a new approach which should look good on most setups I hope!

**Comment by agustif** [comment]
Moved https://github.com/JoinColony/colonyDapp/pull/2848

**Pull request closed without merging**
