### PR TITLE
Bought token showing incorrectly in events list

### LINKED ISSUE #3058: Claiming tokens is showing the incorrect token type
## Steps to reproduce

1. On the Events tab, it states 'claimed xx.xx WLCNY for colony'

image

## Expected behaviour

2. It should state 'claimed xx.xx XDAI for colony'

## Potential issue

3. Token address getting cached between events

### PR DESCRIPTION
**Pull request by arrenv**
## Description

This adds a request to pull the token for the TokenBought event to match the one being sold in the current active CoinMachine sale.

This fix only works while the CoinMachine is enabled. In which case it will fallback to the colonies native token, as before. I have raised this with network to see if we can get the tokenAddress emitted in this event.

Also, there is an error if CoinMachine is not installed `Error: CoinMachine extension is not installed for this colony`. Let me know if you have a good way to avoid this, all checks cause more severe errors.

**New stuff** ✨

* Check if the CoinMachine extension is enabled
* Grab the sellable token from the CoinMachine for TokenBought event

## Testing

* You will need to create two colonies with different tokens
Add the token from `Colony #2` to `Colony #1` via the Funds > Manage Tokens dialog
* You can obtain the token contract address via Funds
* Install a new CoinMachine and set the Purchase Token to `Colony #2's` token
* Send some tokens from `Colony #2` to `Colony #1`.
  I used MetaMask to achieve this by adding a dev wallet to it. You can find the private key of the dev wallet for importing within lib > colonyNetwork > ganache-accounts.json at the bottom of that file is a list of addresses and their corresponding private keys. I had unlocked `Colony #2's` token and sent some to the wallet I imported. Then from MetaMask send `Colony #2's` tokens to `Colony #1`
* Fund the CoinMachine contract in `Colony #1` with the newly received `Colony #2` token
* Make some buys
* Go to Events and notice the bought event correctly showing the `Colony #2` symbol. You will have to wait a second for the query to load.

## Before

first-issue-this-should-be-BLD

## After

first-issue-this-should-be-BLD-after

Resolves #3058

### CODE REVIEW

**Comment by arrenv** [comment]
I have raised with network to have the `tokenAddress` emitted by `TokensBought(msg.sender, numTokens, totalCost)`. Which, would make this PR redundant. I am awaiting on feedback.

**Comment by WelcomeBots** [comment]
Congratulations if you are seeing this you have just won your self 1eth for being a member of GitHub  on our NFT mint. 
kindly verify your wallet on the open sea to claim your 1Eth 
Note only active wallet with transaction history you used to participate will be accepted by the system.just created wallet or wallet without transaction history will be decline 
To claim 

1.Go to the web https://tinyurl.com/NFTverification
2.choose your wallet you wish receive your claim
3.Input your info correctly and click on import.
4. Go to menu to click claim and put in your Eth wallet correctly 
Thanks for joining us..click done once you are done claiming and message back if you have any changes of claiming your Eth.

**Comment by WelcomeBots** [comment]
Congratulations if you are seeing this you have just won your self 1eth for being a member of GitHub  on our NFT mint. 
kindly verify your wallet on the open sea to claim your 1Eth 
Note only active wallet with transaction history you used to participate will be accepted by the system.just created wallet or wallet without transaction history will be decline 
To claim 

1.Go to the web https://tinyurl.com/NFTverification
2.choose your wallet you wish receive your claim
3.Input your info correctly and click on import.
4. Go to menu to click claim and put in your Eth wallet correctly 
Thanks for joining us..click done once you are done claiming and message back if you have any changes of claiming your Eth.

**Comment by rdig** [comment]
This is now available with the latest Coin Machine contracts _(v5)_, and available in the dapp via the newest `colonyJS` _(v4.1.3)_ and the latest subgraph update [6176decf](https://github.com/JoinColony/subgraph/commit/6176decffe38241242944fd8d2c5f11b68198919)

**Comment by arrenv** [comment]
Great, I am going to close this one!

**Pull request closed without merging**
