### PR TITLE
Use transaction token instead of colony token

### LINKED ISSUE #2707: Incorrect token symbol rendering in action list
## Steps to reproduce

View this action [this action](https://xdai.colony.io/colony/agaveswarm/tx/0xbf97bee35324867e3cde930bcc577b2aa122238d1f347f1300fb9aed795e9410) from within the action page, and on the action list.

## Expected behaviour

Should show up as xDai on the action list.

## Actual behaviour

Shows up as AGVE

### PR DESCRIPTION
**Pull request by alicjakujawa**
## Description

This PR fixes wrongly displayed token symbol when transferring funds 

**Changes** 🏗

* Updated ActionsListItem to use correct token
* Updated colonyActions for MoveFunds action to pass transactionToken

Resolves #2707

### CODE REVIEW

**Review by rdig — CHANGES_REQUESTED** [review]
This is still not showing for me, as the token symbol is not showing in the list for ETH/XDAI

Here's a demo:
bug-payment-symbol-not-showing

Here is what I did:
- Send 10 ETH from a Ganache account to the colony
- Claimed the ETH to the colony _(events page)_
- Created a payment for 0.5 ETH for the user

I tried the same with the native token, but that seems to work fine.

**Comment by alicjakujawa** [comment]
> This is still not showing for me, as the token symbol is not showing in the list for ETH/XDAI
> 
> Here's a demo:
> bug-payment-symbol-not-showing
> 
> Here is what I did:
> 
> * Send 10 ETH from a Ganache account to the colony
> * Claimed the ETH to the colony _(events page)_
> * Created a payment for 0.5 ETH for the user
> 
> I tried the same with the native token, but that seems to work fine.

Good catch, fixed

**Review by chinins — APPROVED** [review]
Looks good!

**Review by rdig — APPROVED** [review]
Good to go!

**Pull request merged**
