### PR TITLE
Create Mobile Responsive Actions Menu

### LINKED ISSUE #3477: Create mobile responsive Actions menu on Colony Home page
## Specification

Relates to: https://github.com/JoinColony/colonyDapp/issues/3474
Relies on: https://github.com/JoinColony/colonyDapp/issues/3475

### Story

When creating actions on my mobile, I would like the actions modal to be usable on the smaller screen. 

### Description 

This issue is for screen 6 of the [Figma design](https://www.figma.com/file/DjVCPq7LpkjEMEfQZtKgBdC1/Style-Guide?node-id=6645%3A10726).

### Design 

image

### This issue is complete when...

- [ ] The actions menu responds to screen sizes at or less than `768px` in width

### PR DESCRIPTION
**Pull request by willm30**
## Description

This PR relates to the Actions modal for mobile.

**Changes** 🏗

- [x] Style Actions Modal

## Screenshots

**_Actions modal on mobile_**

actions-mob

Resolves #3477

### CODE REVIEW

**Comment by rdig** [comment]
Talk to @arrenv about this, as I think this might not be necessary.

It looks good as it is _(with minor tweaks, that is)_

**Comment by willm30** [comment]
@arrenv This is how the actions menu currently looks. In the body of the PR is a screenshot of the proposed change per the design spec. Should I go ahead with this change or leave as is?

actions

**Comment by arrenv** [comment]
> @arrenv This is how the actions menu currently looks. In the body of the PR is a screenshot of the proposed change per the design spec. Should I go ahead with this change or leave as is?

You could reduce the padding slightly within the dialog, but otherwise, yeah this looks fine.

**Review by rdig — APPROVED** [review]
I actually liked the original padding personally. But I'm not going to argue this since I don't care _that_ much about it. Feel free to leave it as it is.

Nice work Will!

**Review by ArmandoGraterol — APPROVED** [review]
Looks good to me :ok_hand:

**Pull request merged**
