### PR TITLE
Remove Program and Levels feature

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
Remove program and levels (Also persistent tasks because it's related to levels) features from the colony dapp

I know it's too much code, but please check the code attentively in case I forgot to delete something, or I deleted something that I shouldn't have.

**Deletions** ⚰️

* Basically any code related to program, levels, persistent task

Contributes to DEV-22

### CODE REVIEW

**Review by rdig — CHANGES_REQUESTED** [review]
This also has a server part that you need to remove: resolvers, queries, mutations, apis

This isn't ready until then. _(unless you pushed the server branch and I missed it)_

Also, I think you added `src/img/icons.zip` by mistake:

Screenshot from 2020-12-17 15-59-18

**Comment by ArmandoGraterol** [comment]
> This also has a server part that you need to remove: resolvers, queries, mutations, apis
> 
> This isn't ready until then. _(unless you pushed the server branch and I missed it)_
> 
> Also, I think you added `src/img/icons.zip` by mistake:
> 
> Screenshot from 2020-12-17 15-59-18

Should the code of the server be removed in this branch's submodule? Or do I need to make a PR on the colony server repo?

**Comment by rdig** [comment]
> Should the code of the server be removed in this branch's submodule? Or do I need to make a PR on the colony server repo?

1. you remove it in the server repo _(yes, create a branch and a PR -- this needs to also update the server's package version)_
2. after that's removed, update the server submodule in the dapp with the server branch you've created above
3. commit the above change (otherwise it won't be preserved)
3. submit the (both server and app) for review
4. after it's approved
5. merge the server into it's `master`
6. come back to the dapp and update the server submodule with latest `master` commit hash
7. commit the above change (otherwise it won't be preserved)
8. merge the dapp PR

**Review by rdig — CHANGES_REQUESTED** [review]
- Please rebase this branch on the latest `master`, as it stands it's really hard to review
- Please update the server submodule with the latest changes that remove the program feature on that side
- Please also remove the program and levels features from the graphql fragments

**Comment by rdig** [comment]
Can this be re-reviewed? Or is it still being worked on ?

**Comment by rdig** [comment]
Screenshot from 2021-01-11 09-45-15

Also, please try to keep your commit description's first line under 70 so that it van be properly read.

See: https://www.notion.so/colony/Linear-Github-Git-Workflows-1acdaf1041ee421bb5fc6ecace31096f#96af4a2b85ff4919bc3032153aec3d54

**Comment by ArmandoGraterol** [comment]
> Can this be re-reviewed? Or is it still being worked on ?

@rdig Yeah! Apart from the commit message you pointed out, the rest is ready for review

**Review by rdig — CHANGES_REQUESTED** [review]
This is all good! Very nice work!

I didn't approve this because the server PR still needs work. After that is done I will approve both of them, as you need to merge that first, then update the `colonyServer` submodule here with the latest master commit, then merge this.

**Review by rdig — APPROVED** [review]
Good to go. 

1. Please merge the server PR first
2. Then update this PR with the latest server submodule, but from master
3. Then you merge this as well

**Pull request merged**
