### PR TITLE
Feat: Remove BetaCautionAlert

### PR DESCRIPTION
**Pull request by Julianahlk**
## Description

This PR removes the BETA alert that appears in the footer of the DApp. 

**Changes** 🏗

* Removed the `BetaCautionAlert` component and removed all instances where this component was used.

**Deletions** ⚰️

* `BetaCautionAlert` component.

Resolves #3554

### CODE REVIEW

**Comment by willm30** [comment]
FYI this PR is still in draft mode but when you select people for review it notifies them straightaway so best to wait until after you've clicked `Ready for review` 🙂

**Comment by Julianahlk** [comment]
@willm30 Good to know! Thank you

> FYI this PR is still in draft mode but when you select people for review it notifies them straightaway so best to wait until after you've clicked `Ready for review` 🙂

Hey @willm30 good to know! This PR is actually ready but I forgot to click the ready for review button earlier. 😅

**Comment by willm30** [comment]
Also don't forget to link the PR to the correct issue at the bottom, e.g. `Resolves #1234` 🙂

**Review by willm30 — APPROVED** [review]
Looks good to me!

**Comment by rdig** [comment]
@Julianahlk 

Screenshot from 2022-06-29 13-40-25

Don't label PRs, just issues. 

Since the issue has the correct labels, and the PR is attached to the issue _(as Will pointed out above)_, there's no point in re-labeling

**Review by rdig — APPROVED** [review]
All good here. Good to go! :+1:

**Pull request merged**
