### PR TITLE
Add `Smite` feature

### PR DESCRIPTION
**Pull request by chinins**
## Description

This PR is for `Smite` feature implementation.

Corresponds to `Smite` project & all cascading issues.

### CODE REVIEW

**Comment by rdig** [comment]
While reviewing @ArmandoGraterol 's #2770 I came across this:

The user's  that "smote" (created the smite action), avatar doesn't show up properly. It's generated based on `AddressZero`:
Screenshot from 2021-11-02 16-22-01

But inside the action page, everything's good.

This needs to be address before going to QA

**Comment by rdig** [comment]
Found another thing:
- The Smite dialog should have the first colony user already selected in the picker _(as we do in the Permissions dialog)_

Currently it is not:
Screenshot from 2021-11-02 16-42-04

**Review by rdig — APPROVED** [review]
:+1:

**Review by ArmandoGraterol — APPROVED** [review]

**Review by arrenv — APPROVED** [review]
@chinins Great work! May all who do wrong be smite'd.

**Pull request merged**
