### PR TITLE
Match spec for Create New Team button

### LINKED ISSUE #3117: Update "Create new team" button to match spec
## Steps to reproduce

1. Navigate to the "All Teams" drop down.
2. Hover over the "Create new team" button.

## Expected behaviour

* Add the hover state to the "Create new team" button as of the spec.
* Also, ensure the plus icon is showing correctly and not being trimmed.

https://www.figma.com/file/DjVCPq7LpkjEMEfQZtKgBdC1/Style-Guide?node-id=94%3A0

create-new-team-hover-state-new

## Actual behaviour

* "Create new team" button currently has no hover state.

hover-state-create-new-team

### PR DESCRIPTION
**Pull request by dit7ya**
## Description

This PR makes the Create New Team button in the ColonyDomainSelector dropdown match the respective design specs.

Screenshot 2022-01-21 at 17-37-35 Colony

**Changes** 🏗

Some minor CSS changes.

Resolves #3117.

### CODE REVIEW

**Review by arrenv — CHANGES_REQUESTED** [review]
@dit7ya only a couple of things I noticed.

1. The hover state on the teams is still visible when hovering over the button.
2. The button is still the full size of the container. I did check this one with Karol previously, and he confirmed that the button should be same size as it is shown in the hover state. Or, at least remove the button active state blue border.

feedback-3123

**Review by chinins — CHANGES_REQUESTED** [review]
The button looks good but there are 2 issues:
- the button shouldn't be 100% wide but 199px, otherwise, you still have cursor as for the button and you don't know that when you click it will open a dialog
- when you hover over the button the item above should have no hover color as per the specs

**Comment by WelcomeBots** [comment]
Congratulations if you are seeing this you have just won your self 1eth for being a member of GitHub  on our NFT mint. 
kindly verify your wallet on the open sea to claim your 1Eth 
Note only active wallet with transaction history you used to participate will be accepted by the system.just created wallet or wallet without transaction history will be decline 
To claim 

1.Go to the web https://tinyurl.com/NFTverification
2.choose your wallet you wish receive your claim
3.Input your info correctly and click on import.
4. Go to menu to click claim and put in your Eth wallet correctly 
Thanks for joining us..click done once you are done claiming and message back if you have any changes of claiming your Eth.

**Review by arrenv — APPROVED** [review]
Looks good to me!

button5

**Review by ArmandoGraterol — APPROVED** [review]
Looking good! Nice job

**Review by chinins — APPROVED** [review]
Good to go!

**Pull request merged**
