### PR TITLE
Whitelist UI dialog styles fix

### LINKED ISSUE #3245: Manage whitelist dialog UI updates
## Things to fix

1. Tabs border alignment 
Screenshot 2022-03-16 at 11 52 47

1. Modal content (we should be able to scroll content)
Screenshot 2022-03-16 at 11 52 58

### PR DESCRIPTION
**Pull request by dit7ya**
## Description

Made some styling changes.

For the context of the first screenshot see here - https://github.com/JoinColony/colonyDapp/pull/3220#issuecomment-1068964332

Resolves #3245.

### CODE REVIEW

**Review by alicjakujawa — CHANGES_REQUESTED** [review]

**Review by arrenv — APPROVED** [review]
Looks good on my end. I think you just need to confirm Alicja's feedback.

05b5cabe-0a44-49ff-a436-343754133488

**Review by ArmandoGraterol — APPROVED** [review]
LGTM :ok_hand:

I agree with Alicja, if the change is only needed in 1 dialog, it's best to avoid changing the core component just in case

**Comment by dit7ya** [comment]
@alicjakujawa I actually forgot to write about that in the PR. I wanted to ask @ArmandoGraterol about that change since that CSS was introduced by them just a month ago and is part of this project only. I thought changing that in the component will save us from having similar bugs when we use this component in other places in future. Of course I might be wrong. What do you think @ArmandoGraterol ?

**Comment by ArmandoGraterol** [comment]
> @alicjakujawa I actually forgot to write about that in the PR. I wanted to ask @ArmandoGraterol about that change since that CSS was introduced by them just a month ago and is part of this project only. I thought changing that in the component will save us from having similar bugs when we use this component in other places in future. Of course I might be wrong. What do you think @ArmandoGraterol ?

I wrote that when I implemented the tooltip in the `Whitelisted` section because the tooltip would get cut off by the Dialogs always hiding the overflow. 

Currently, this change you made should only affect the manage whitelist dialog as far as I remember. Now it seems like the tooltip is not getting cut off anymore with or without your change **and** my change, so with that being said, I tested changing the `auto` back to `initial` and resized my screen to a smaller screen and it seems like your change is solving the modal not having a scroll in the smaller screens so I'm good with it :+1:

**Review by alicjakujawa — APPROVED** [review]

**Pull request merged**
