### PR TITLE
Add release milestone

### LINKED ISSUE #3716: Expenditures: As a user I can release a milestone
[Provided by Adrian via Contractors project management platform]

## Description
User has to be able to release a milestone in any order. After releasing a milestone, user should see "Completed" label.

## Acceptance Criteria

- an option to display and click "Release" button
- "Release" button is placed below silder
- an option to display a "Completed" label

## Design

- [Figma Link - Can release milestones](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3746%3A314833)
- [Figma Link - Released milestone](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3802%3A280428)

reject)

reject)

### PR DESCRIPTION
**Pull request by agnieszkajarosikloj**
## Description

This PR adds ability to release a milestone in any order. After releasing a milestone, "Completed" label is displayed.

[Figma Link - Can release milestones](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3746%3A314833)
[Figma Link - Released milestone](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=3802%3A280428)

Resolves  #3716

### CODE REVIEW

**Review by Julianahlk — COMMENTED** [review]
When going through the release flow:
 I soon as create a motion, multiple Formik context warning show up in the console. These number of warnings increase as I click on the release buttons and the claim button as well.
 
release

**Comment by willm30** [comment]
Working well for me, but I'm also seeing the same errors/warnings in the console as Juliana. I think it would be good to clear these up.

**Comment by agnieszkajarosikloj** [comment]
@Julianahlk  @willm30  thanks for comments. Warning about undefined Formik context is showing up because I haven't merged yet the [PR](https://github.com/JoinColony/colonyDapp/pull/3609) with fix. In this PR I split Stages component into 'FormStages' and 'LockedStages', to avoid calling the 'useFormikContext' hook outside of formik context.

**Comment by Julianahlk** [comment]
> @Julianahlk @willm30 thanks for comments. Warning about undefined Formik context is showing up because I haven't merged yet the [PR](https://github.com/JoinColony/colonyDapp/pull/3609) with fix. In this PR I split Stages component into 'FormStages' and 'LockedStages', to avoid calling the 'useFormikContext' hook outside of formik context.

Thanks for the explanation @agnieszkajarosikloj, looks good 👍.

**Review by Julianahlk — APPROVED** [review]

**Comment by willm30** [comment]
@agnieszkajarosikloj When I have three milestones and click "Release" on them all, the "completed" label disappears on all -- is that by design?

**Comment by agnieszkajarosikloj** [comment]
@willm30  I've added a change and now "Completed" button is also visible in the "Released" stage.

**Review by ArmandoGraterol — APPROVED** [review]
Looks good to me! Nice work :ok_hand:

**Pull request merged**
