### PR TITLE
Refresh sales data period query after extension install

### LINKED ISSUE #2970: Fix caching issue in previous sales table
Currently when we reinstall coin machine extension we see old data in previous sales widget. We need to refresh page in order to cleans this up

### PR DESCRIPTION
**Pull request by alicjakujawa**
## Description

This PR fixes PreviousSalesTable widget caching issue. It was showing data from previous sales (but from last coin extension address) after coin machine extension reinstall

**Changes** 🏗

* Updated refreshExtension to update SalesPeriodData after coin machine extension install

Resolves #2970

### CODE REVIEW

**Review by arrenv — COMMENTED** [review]
Hi @alicjakujawa what is the best way to replicate the issue to test?

I have tried customising the Coin Machine extension parameters, depreciating, uninstalling the extension. Then re-ininstalling and enabling with new parameters, however, it shows with the correct new details, without a refresh.

**Comment by alicjakujawa** [comment]
> Hi @alicjakujawa what is the best way to replicate the issue to test?
> 
> I have tried customising the Coin Machine extension parameters, depreciating, uninstalling the extension. Then re-ininstalling and enabling with new parameters, however, it shows with the correct new details, without a refresh.

1. Install coin machine, send tokens to coin machine address
2. Buy tokens
3. Make sure that you have data in previous sales table
4. Reinstall coin machine extension
5. Go back to Coin machine page and see previous sales data

**Review by arrenv — APPROVED** [review]
Thank you. Mine was refreshing. I was able to replicate though and see that your fix works great!

### Before
before-cached-sales-data

### After

after-cached-sales-data

**Review by ArmandoGraterol — APPROVED** [review]
Working as expected!

**Review by rdig — APPROVED** [review]
Good to go

**Pull request merged**
