### PR TITLE
Add new tooltip lib; override styles to fit our app

### LINKED ISSUE #3238: Fix tooltip issue in whitelisted addresses tab
Just hover over item. Tooltip is not always shwoing

### PR DESCRIPTION
**Pull request by alicjakujawa**
## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

Screenshot 2022-04-01 at 14 41 41

Resolves #3238

### CODE REVIEW

**Review by rdig — APPROVED** [review]
I'm ok with this, adding a new library.

But if we make the change here, might as well add it in all the Dapp tooltips

**Comment by danbr** [comment]
> I'm ok with this, adding a new library.
> 
> But if we make the change here, might as well add it in all the Dapp tooltips

@alicjakujawa @rdig FYI......
@arrenv and I discussed issues and limitations around our tooltips here (https://github.com/JoinColony/colonyDapp/pull/3242), and considered using tippy (https://atomiks.github.io/tippyjs/)

**Comment by alicjakujawa** [comment]
> > I'm ok with this, adding a new library.
> > But if we make the change here, might as well add it in all the Dapp tooltips
> 
> @alicjakujawa @rdig FYI...... @arrenv and I discussed issues and limitations around our tooltips here (#3242), and considered using tippy (https://atomiks.github.io/tippyjs/)

I mean if you think that tippyjs lib is better than i don't have any preferences. But you would need to make this refactor quite soon, as this feature will go to QA probably somewhere next week

**Comment by danbr** [comment]
> > > I'm ok with this, adding a new library.
> > > But if we make the change here, might as well add it in all the Dapp tooltips
> > 
> > 
> > @alicjakujawa @rdig FYI...... @arrenv and I discussed issues and limitations around our tooltips here (#3242), and considered using tippy (https://atomiks.github.io/tippyjs/)
> 
> I mean if you think that tippyjs lib is better than i don't have any preferences. But you would need to make this refactor quite soon, as this feature will go to QA probably somewhere next week

I have no preference either, and have not made any investigation or comparison to either of the options. 
So I dont feel informed enough to call a winner out of the 2. 

It was just to let you know that we also had issues with the current implementation.

**Comment by alicjakujawa** [comment]
> > > > I'm ok with this, adding a new library.
> > > > But if we make the change here, might as well add it in all the Dapp tooltips
> > > 
> > > 
> > > @alicjakujawa @rdig FYI...... @arrenv and I discussed issues and limitations around our tooltips here (#3242), and considered using tippy (https://atomiks.github.io/tippyjs/)
> > 
> > 
> > I mean if you think that tippyjs lib is better than i don't have any preferences. But you would need to make this refactor quite soon, as this feature will go to QA probably somewhere next week
> 
> I have no preference either, and have not made any investigation or comparison to either of the options. So I dont feel informed enough to call a winner out of the 2.
> 
> It was just to let you know that we also had issues with the current implementation.

Great, so i will create issue for refactoring existing tooltip by using this tooltip, unless person which pick this up will find out that there are better options - then will use this option

**Pull request merged**
