### PR TITLE
Add welcome modal

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
Added welcome dialog to coin machine page (Only UI)

FireShot Capture 389 - Colony - localhost

Resolves DEV-452

### CODE REVIEW

**Comment by rdig** [comment]
Even though this issue was spec'd out, We're not implementing this modal anymore.

Please confirm with product, but last I remember from the handover call, this will not be implemented.

**Comment by rdig** [comment]
@ArmandoGraterol why did you put this on hold? If we're not doing it anymore, might as well close the PR

**Comment by ArmandoGraterol** [comment]
> @ArmandoGraterol why did you put this on hold? If we're not doing it anymore, might as well close the PR

@rdig It was mentioned in the product channel that we wouldn't use it "_for now_", so I put it on hold just in case. I don't have any problem closing it otherwise

**Comment by rdig** [comment]
Nah, don't worry about it. Just close it _(as you already did)_ and if need be, we'll create a new PR

**Pull request closed without merging**
