### PR TITLE
Better handling of long usernames

### LINKED ISSUE #2967: Address cut off on AddressWidget in action transaction
## Steps to reproduce

1. Perform a Payment action

## Expected behaviour

* Should show the full address

## Actual behaviour

* Part of the address is being cut off by forced column width.

address-cut-off-in-transaction

## Suggestions (optional)

* Could wrap the address and colony name to separate lines

### PR DESCRIPTION
**Pull request by arrenv**
## Description

There are various locations in the Dapp where if a long username is used, the interfaces breaks. This PR aims to better handle instances where long usernames are used.

The following screenshots demonstrate some of the worst instances of the current affects of long usernames.

broken-long-usernames-2
broken-long-usernames-3
broken-long-usernames

**New stuff** ✨

* A new global CSS class has been added to Popover, to allow targeting of child components. This is not essential, although, allows for longer usernames in the popover.

**Changes** 🏗

* Various stylings have been updated to better handle long usernames.
* Ellipsis or multiline layouts have been used where required.

The following screenshots demonstrate the improved handling of long usernames.

handle-long-usernames-8
handle-long-usernames-4
handle-long-usernames-9
handle-long-usernames-3
handle-long-usernames-2
handle-long-usernames-5
handle-long-usernames-6
handle-long-usernames
handle-long-usernames-10
handle-long-usernames-7
handle-long-usernames-11

Resolves #2967

### CODE REVIEW

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
Good work! I think there's only 1 spot left that needs to be updated:

FireShot Capture 505 - Colony - localhost

**Comment by arrenv** [comment]
> Good work! I think there's only 1 spot left that needs to be updated:

Thanks for picking that one up. I wonder if that would be better to not have those extension details as a table. I will try a couple of things.

**Comment by arrenv** [comment]
@ArmandoGraterol thanks again. I have updated that section within the table. As well another section I found with the display name.

handle-long-usernames-12

handle-long-usernames-13

**Review by rdig — APPROVED** [review]
All good! Nice work! :100:

**Review by ArmandoGraterol — APPROVED** [review]
Nice work! I found another place where you might need to do make some changes, but after applying that change I think this should be good to go so I'm pre-approving

This is how the whitelist approved addresses looks when the username is long, the item list now has a horizontal scroll, which I think is not a good UX :P Should be shortened as well
FireShot Capture 506 - Colony - localhost

**Comment by arrenv** [comment]
Thank you @ArmandoGraterol, I will fix this one up and also do another look over the Dapp.

I will also raise an issue in future for there be a consistent component for handling usernames and the sizing issue.

**Comment by arrenv** [comment]
I have updated a couple more locations, including the one you found @ArmandoGraterol.

handle-long-usernames-14

handle-long-usernames-15

handle-long-usernames-16

**Pull request merged**
