### PR TITLE
Add cancelled state

### LINKED ISSUE #3895: Expenditures: As a user I can see a cancelled state
[Provided by Adrian via Contractors project management platform]

## Description
User has to be able to see updated state after canceling the payment.

## Acceptance Criteria

- an option to see an "Cancelled" state
- an option to see "Claim funds" button
- an option to see "Paid to date" funds and currencies
- an option to see "Available to claim" funds and currencies
- an option to see a "passed" state below linked motions

## Design

- [Figma Link - Cancelled state](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=5732%3A327154)

Screenshot 2022-09-23 165628

### PR DESCRIPTION
**Pull request by agnieszkajarosikloj**
## Description

This PR adds cancelled state after canceling the payment.

[Figma Link - Cancelled state](https://www.figma.com/file/dCtvv76S8mk5HNApjwmBto/Expenditures?node-id=5732%3A327154)

Screenshot 2022-10-07 at 00 03 20

Resolves  #3895

### CODE REVIEW

**Review by Julianahlk — COMMENTED** [review]
Is the Claim funds button supposed to be enabled after you cancel a streaming? 
Screen Shot 2022-10-13 at 9 49 38 AM

Also, in the designs I see there is a third icon, are you planning on adding it in the future?
Screen Shot 2022-10-13 at 9 52 01 AM

**Comment by agnieszkajarosikloj** [comment]
@Julianahlk 
1. After cancelling a streaming payment, there still should be a possibility to claim funds.
2. I didn't add the icon, because it's out of scope of our work in phase-3. We didn't include "waiving/forfeiting option" in our estimations. @arrenv Could you confirm it?

**Review by Julianahlk — APPROVED** [review]
Just waiting to hear back from Arren regarding your last comment but otherwise, this PR looks good to me. Good work 👍.

**Review by chinins — APPROVED** [review]
All good, nice work!

**Pull request merged**
