### PR TITLE
Consistent font sizing and alignment in UserNavigation

### LINKED ISSUE #3159: Make fonts size and alignment consistent in UserNavigation
## Description

Currently, the font sizing and alignment in the UserNavigation is inconsistent. The design spec calls for all font sizing to be 13px and vertically centered, however, we currently have both 13px and 14px used.

## Expected behaviour

* All font sizing and alignment should match the design spec - [Figma link](https://www.figma.com/file/DjVCPq7LpkjEMEfQZtKgBdC1/Style-Guide?node-id=2905%3A0)

fonts-size-alignment

## Actual behaviour

* The font sizing and alignment is inconsistent.

current-size-alignment

### PR DESCRIPTION
**Pull request by arrenv**
## Description

This PR aims to make the sizing and alignment of fonts consistent in the UserNavigation.

user-navigation-alignment

**New stuff** ✨

* New element wrapper for all elements in the UserNavigation

**Changes** 🏗

* Various styling updates 

Resolves #3159

### CODE REVIEW

**Review by dit7ya — CHANGES_REQUESTED** [review]
The navbar looks good to me except a (very) minor misalignment on the wallet button (it is slightly shifted upwards). I think it is practically unnoticeable to the regular user.



However, I noticed that due to changes in the `MemberReputation` component it is broken in other places.

- Cramped






- Misaligned

**Comment by arrenv** [comment]
@dit7ya thank you for finding that. The reputation should now be fixed. Please confirm.

Regarding the address, I wasn't seeing the same issue exactly, something to do with the font rendering differences probably. However, let me know if what I changed helps on your end.

**Comment by chinins** [comment]
By the way, reputation in other places looks ok.

**Comment by arrenv** [comment]
@chinins I have made an update, can you let me know if that helps on your end.

@dit7ya Can you please also double check, given I have made a change.

**Comment by dit7ya** [comment]
Just tested, everything seems fine. :+1:

**Review by chinins — COMMENTED** [review]
Still the address is not aligned
Screenshot 2022-03-03 at 18 40 29

**Comment by arrenv** [comment]
@chinins I have added another variation. Please let me know how this looks.

If it does not work, could you please show what it looks like with the button element highlighted. For example the screenshot below:

730b7b6e-4ad5-45c1-9782-f069bc9095ac

**Review by ArmandoGraterol — APPROVED** [review]
In my machine, it's also looking good, as Sayan's screenshot :+1:

**Review by chinins — APPROVED** [review]
Looks perfect now. Well done! These issues are always very difficult to solve :
Screenshot 2022-03-04 at 13 45 47
)

**Pull request merged**
