### PR TITLE
Add Manage Funds Index Modal

### PR DESCRIPTION
**Pull request by rdig**
## Description

This PR adds in the Manage Funds Index Modal, as this is a pre-requisite for wiring up the _"Move Funds Between Domains"_ action in DEV-64

**Changes** 

- [x] Added `emoji-medal` icon
- [x] Added `emoji-pen` icon
- [x] Added `emoji-piggy-bank` icon
- [x] Added `emoji-seed-sprout` icon
- [x] Added `emoji-world-globe` icon
- [x] Added `ManageFundsDialog` component
- [x] Initial wiring of `ManageFundsDialog` and `TransferFundsDialog` inside `ColonyHomeActions`

**Demo**

cs-demo-mange-funds-index-modal

Resolves #DEV-63

### CODE REVIEW

**Review by alicjakujawa — COMMENTED** [review]
I was testing modal. I have some thoughts. So in Create expenditure flow, if we don't have required permissions, we're displaying this message with missing permisison at the top of Payment modal. Also fields are disabled.
This modal is missing those, so question is, 
Is it in scope of this task?

**Comment by rdig** [comment]
> at the top of Payment modal

I don't understand this

> Also fields are disabled.

The only fields that are disabled are the "coming soon" ones

**Comment by alicjakujawa** [comment]
> > at the top of Payment modal
> 
> I don't understand this
> 
> > Also fields are disabled.
> 
> The only fields that are disabled are the "coming soon" ones

Screenshot 2020-12-15 at 12 48 41

**Comment by rdig** [comment]
> <Image ...>

Now I understand :)

No, this is out of scope here. It's going to be tackled in #2327

**Review by alicjakujawa — APPROVED** [review]

**Pull request merged**
