### PR TITLE
Adds icon arrow-right for manage funds link

### LINKED ISSUE #2814: Fix 'Manage Funds' link alignment
The arrow symbol to the left of the the _Manage Funds_ link on the Colony Home is misaligned for some _(all?)_ machines.

This is a cross OS, cross Machine or cross Resolution issue, so please ensure this will render properly no matter on which machine we try to render.

Note that we only support Chorme officially _(and Chrome based browsers unofficially)_ so you don't really have to bother with how it renders on anything else other than Chrome.

The component you need to be targeting is `ColonyTotalFunds`

Here's some examples of the problem:

I'd say this one is "ok-ish" in terms of alignment _(Linux, 1x Pixel Density, 100% Zoom)_
Screenshot from 2021-10-24 22-58-35

But when you zoom in, it starts to break down _(Linux, 1x Pixel Density, 250% Zoom)_
Screenshot from 2021-10-24 23-10-40

However, this one is clearly misaligned _(Linux, 2x Pixel Density, 100% Zoom)_
Screenshot from 2021-10-24 22-58-24

### PR DESCRIPTION
**Pull request by agustif**
## Description

- Changes arrow right icon from unicode to svg using Icon component, fixes css where appropiate.

**New stuff** ✨
* added icon arrow-right as svg
* uses <Icon />

**Changes** 🏗

* rightArrowDisplay css changed

**Deletions** ⚰️
* `<span> *arrow* </span>` deleted

**Screenshots**
image

Resolves #2814

### CODE REVIEW

**Review by chinins — COMMENTED** [review]
Looks ok on my machine but I would like for Raul and Armando to confirm that this looks ok on their machines as well.

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
It's almost there for me:

FireShot Capture 498 - Colony - localhost

It looks like it needs to be moved 1px or 2px more to the top for it to be centered with `Manage Funds`

**Comment by chinins** [comment]
> It's almost there for me:
> 
> FireShot Capture 498 - Colony - localhost
> 
> It looks like it needs to be moved 1px or 2px more to the top for it to be centered with `Manage Funds`

@ArmandoGraterol, I thought it might be too low but not sure.

@agustif, can you please try lifting the arrow 1 or 2 px as Armando suggested and submit a version that you think looks the best.

**Comment by agustif** [comment]
Went for 1px as margin-bottom as with 2px when in high zooms it would look too high to me

image

Rebasing now so it can be merged if it looks OK to you @chinins and @ArmandoGraterol

**Review by chinins — APPROVED** [review]
looks better now

**Review by ArmandoGraterol — APPROVED** [review]
Looking good :ok_hand: Nice work! Should be good to merge now

**Pull request merged**
