### PR TITLE
Flesh out DetailsWidget of motion page

### PR DESCRIPTION
**Pull request by ArmandoGraterol**
## Description

- Add details to DetailsWidget of motion page

**New stuff** ✨

* Added MintTokenMotions emoji and details

**Changes** 🏗

* Added dynamic message-id to DetailsWidget to cover motion titles

## TODO

- Add the details for the other motions when they are ready

FireShot Capture 257 - Colony - localhost

Resolves DEV-300

### CODE REVIEW

**Review by alicjakujawa — APPROVED** [review]
Screenshot 2021-05-05 at 18 11 07
Works good, the only think i would double check if we want so big space between those 2 widgets (double check with product)

**Comment by ArmandoGraterol** [comment]
> Screenshot 2021-05-05 at 18 11 07
> 
> Works good, the only think i would double check if we want so big space between those 2 widgets (double check with product)

Hmmm ... I feel like that white space is where the result of the voting phase should show

**Comment by alicjakujawa** [comment]
> > Screenshot 2021-05-05 at 18 11 07
> > Works good, the only think i would double check if we want so big space between those 2 widgets (double check with product)
> 
> Hmmm ... I feel like that white space is where the result of the voting phase should show

of course, but not in all states :D So we need to find out if this white space should exist for other states

**Review by chinins — APPROVED** [review]
Works well!

**Pull request merged**
