### PR TITLE
Fix manage funds link arrow aligment and positioning

### LINKED ISSUE #2814: Fix 'Manage Funds' link alignment
The arrow symbol to the left of the the _Manage Funds_ link on the Colony Home is misaligned for some _(all?)_ machines.

This is a cross OS, cross Machine or cross Resolution issue, so please ensure this will render properly no matter on which machine we try to render.

Note that we only support Chorme officially _(and Chrome based browsers unofficially)_ so you don't really have to bother with how it renders on anything else other than Chrome.

The component you need to be targeting is `ColonyTotalFunds`

Here's some examples of the problem:

I'd say this one is "ok-ish" in terms of alignment _(Linux, 1x Pixel Density, 100% Zoom)_
Screenshot from 2021-10-24 22-58-35

But when you zoom in, it starts to break down _(Linux, 1x Pixel Density, 250% Zoom)_
Screenshot from 2021-10-24 23-10-40

However, this one is clearly misaligned _(Linux, 2x Pixel Density, 100% Zoom)_
Screenshot from 2021-10-24 22-58-24

### PR DESCRIPTION
**Pull request by agustif**
## Description
- [ ] Fix the alignment of the funding link

**New stuff** ✨
Added a gap: 15px to separate each button on itself Colony total balance / Manage funds

**Changes** 🏗
Moved from margin to flex based align-items: center; for alignment of items.
**Removed** 
Margin for the rightarrowicon

## TODO

- [ x]  Fixes the alignment of the funding link

## Screenshots **Updated**
image
image
image

Resolves #2814

### CODE REVIEW

**Review by rdig — CHANGES_REQUESTED** [review]
On my end it renders too low.

Screenshot from 2021-11-09 21-15-10
Screenshot from 2021-11-09 21-15-18

This might actually be a case where we're going to need to ditch the symbol and replace it an actual svg icon

**Comment by chinins** [comment]
Please, rebase on latest master.

**Comment by ArmandoGraterol** [comment]
> On my end it renders too low.
> 
> Screenshot from 2021-11-09 21-15-10 Screenshot from 2021-11-09 21-15-18
> 
> This might actually be a case where we're going to need to ditch the symbol and replace it an actual svg icon

Yeah, for me it's looking like this too

**Review by chinins — CHANGES_REQUESTED** [review]
It's too low on my machine. Also `Manage funds` is misaligned with the other text... 
Maybe, like Raul said, the emoji is the answer...

Screenshot 2021-11-10 at 13 52 13

**Comment by rdig** [comment]
What's the status of this ?

**Comment by agustif** [comment]
> What's the status of this ?

Will be  pushing it today, moving it to svg icon

**Comment by chinins** [comment]
Any progress on that? When do you think you'll have it fixed?

**Comment by agustif** [comment]
> Any progress on that? When do you think you'll have it fixed?

Pushing final changes, let me check out everything is OK and will send to re-review again!

**Comment by agustif** [comment]
https://github.com/JoinColony/colonyDapp/pull/2959

Closing and opening a new one with cleaner commit history, sorry!!

**Pull request closed without merging**
