### PR TITLE
Add: `/create-colony` mobile styles

### LINKED ISSUE #3576: Create mobile responsive "Create a colony" page
## Specification

Relates to https://github.com/JoinColony/colonyDapp/issues/3481

### Story

When I click "Create a Colony" from Colony Home page hamburger menu on mobile, I want the Create Colony page to be responsive.

### Description

Following the style of the designs (linked in other issues in this project), this issue tracks the work required to make the Create a Colony screen mobile responsive.

### Design 

No design for this specific screen but should follow style of other designs in this project.

### This issue is complete when...

- [ ]  The Create A Colony screen is mobile responsive (max-width: 768px)

### PR DESCRIPTION
**Pull request by willm30**
## Description

This PR tracks the work required for making the `/create-colony` route mobile responsive. No specific design for this route, however should follow the same pattern as other designs in this project. 

**Changes** 🏗

* `StepCreateToken` : add mobile styles
* `StepConfirmAllInput`:  add mobile styles
* `StepColonyName`:  add mobile styles

## Screenshots

**_`/create-colony`: Step 1_**

create-col-1

**_`/create-colony`: Step 2_**

create-col-6

**_`/create-colony` : Create new token_**

create-col-2

**_`/create-colony` : Confirm_**

create-col-3

**_`/create-colony` : Transactions_**

create-col-4

**_`/create-colony` : Use existing token_**

create-col-5

Resolves #3576

### CODE REVIEW

**Review by arrenv — CHANGES_REQUESTED** [review]
Mostly looks good, I noticed a couple of the screens did not fit, maybe because of the longer Colony Name.

download (51)


download (52)


Also, I think we can reduce the padding here to zero:

download (53)

**Comment by willm30** [comment]
@arrenv Have removed the padding. Could you check the other screens again? I think I fixed the wrapping issue in another of the branches, so hopefully a `git pull` should have everything showing up. For reference, mine looks like:
look-right
create-new-tok

**Comment by Julianahlk** [comment]
I tested creating a colony with a long user name and long token name and I am also getting the errors Arren is getting:

Screen Shot 2022-07-08 at 2 49 44 PM
g. 
Screen Shot 2022-07-08 at 2 53 11 PM

This screen looks good though
Screen Shot 2022-07-08 at 2 50 42 PM

**Comment by willm30** [comment]
@Julianahlk Ok thanks, I believe I have fixed this now:

overflow-1
overflow-2

**Review by Julianahlk — APPROVED** [review]

**Review by ArmandoGraterol — APPROVED** [review]
Nice work!

**Review by chinins — APPROVED** [review]
All good!

**Comment by willm30** [comment]
@arrenv Is this branch looking good for you now?

**Review by danbr — CHANGES_REQUESTED** [review]
Looks good overall but found a few subtile issues.....

Tooltip is mostly offscreen:
Screenshot 2022-07-13 at 10 37 15

Link is not highlighted (other links show correctly)
Screenshot 2022-07-13 at 10 44 52

Form fields are shifting when inputs provided
Jul-13-2022 10-50-08

**Comment by willm30** [comment]
@danbr Thanks, should all be fixed now.

**Review by danbr — APPROVED** [review]
Great work... Your updates fixed all the issues. Well done.

**Review by arrenv — APPROVED** [review]
> @arrenv Is this branch looking good for you now?

Looks good to me @willm30, nice work!

**Pull request merged**
